env: testnet
project: elk
app: es-node-01
owners: tianfeng.cui
instance_type: r5.large
ami_id: ami-049f20cccc294bb90
key_name: "cpchain-jumpserver"
snapshort_enabled : false
custom_tags:
  BillingGroup: cpchain
vpc_selector:
  cidr_block: 10.10.0.0/16
  moniker: cpchain-testnet
subnet_selector:
  cidr_block: 10.10.17.0/24  #subnet ip range
ebs_block_device: 
  /data:
    device_name: /dev/sdb
    volume_size: 300
    volume_type: gp3
root_block_device:
  volume_size: 100
vpc_security_group_rules: |
  ingress_with_cidr_blocks: 
  - rule: all-icmp
    cidr_blocks: 10.0.0.0/8
  - rule: all-all
    cidr_blocks: 10.0.0.0/8
    description: allow access from aws internal net
  egress_with_cidr_blocks:
  - rule: all-all
    cidr_blocks: 0.0.0.0/0
node_indices: [41]
private_ips: 
- 10.10.17.41
custom_role_policies: 
inline_role_policies: 
- policy_name: testpolicy
  document: |
    Version: "2012-10-17"
    Statement: 
    - Effect: Allow
      Action: 
      - s3:GetObject
      Resource:
      - arn:aws:s3:::static.cpchain.com
custom_userdata: |
  ##create sshClient_UserConfig file
  echo "Host *" >/root/.ssh/config
  echo "StrictHostKeyChecking no" >>/root/.ssh/config
  echo "UserKnownHostsFile=/dev/null" >>/root/.ssh/config
  echo "" >>/root/.ssh/config
  echo "Host github.com-repo-0" >>/root/.ssh/config
  echo "        Hostname github.com" >>/root/.ssh/config
  echo "        IdentityFile=/root/.ssh/initscript_deploy_key" >>/root/.ssh/config
  ##create initscript_deploy_key file
  cat > /root/.ssh/initscript_deploy_key <<EOF
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpAIBAAKCAQEAyyMT/SNZQ8XPuUoOtOmONcbLP51c7p+mmROwV9CindSsmmYp
  bG6b8Mr4Q8tTzytGyXrmthSwDk4Buhg4iLTMNi0CsfucZgGLJd6ylGllbc63OqU9
  v+3TbEEI69tLu3dNotpjZGBPhE75uvNMU/nGQXuesXJ8a5Q1Wgcf1uPZeGOAdh05
  DhhbmDatGDrLZ1HNqlquDY5PJWk1nPBFb81Gnw/pOg6cw72aFaPx9ELoVG8PnNxT
  vZ9yekmW10OLk7VlqDfwho9D/UfojHIvXDeNhcJUhheWI7v67EVv6I7Q8O/n9xR1
  AMMoTy2RaJZl9N9FEmlgHH+cNXrtC/TQ7tZECQIDAQABAoIBADPM1iQPB4xIvRe6
  0tU/WYxNDTdDoZcYDxup8aXzBgTJXtpggt+rtQhKOdTP3KdPmdV3Ca4UyHBdZANY
  edIiiJCoGa/ZQaChdCJMD63Y0oyV0hOaX4y50NgiHWxHl6BOY/XLSt0l0iEjInuR
  3zzqzKuWInmNgDzOpmw2tN/Pan1QLchl1z3uLWXM0G4Ianj21rzJv95WXVHHSDu/
  ZsZnco4hXlsKUskP+RekCsTPpTawMXAzZDe51qU1vfhdBiM5OAoJnjW5gdD+pYPa
  BaSkUSqJXRhtuZpNoAxxaT5tSj1guQU3/diumc1FvB3foCReMOy9GxxRinyHWnh/
  /M40TAECgYEA8eaCeNSTDH+1IgkKdr+Z2Sf6G6x+BMkt2+juE8MGGrJ4Xtl0b2aU
  i48xR19DbT7otFeeKZcdwp7wlbUbdBE1baguw0Tk8qdTAu6qgn14NxRSUm/703A1
  SxUehG0fvp6M9s0u1XEvs+6xgGwVZXgYE+LzBBQwuS48im2WeiMjlLkCgYEA1voq
  ItEmh4dge5Momj2StJteiirNck7tIoLAGk1XZPIL5CLzbKsuK7J8buODbrt+JNqN
  oTfQwSaGLOlfI2SbvKM+HPfGJJFieftpqLlXNOIE6HJXxv1u/9TsgCI+Cu2blUkC
  ITR0qEcAhJ15ERez3wjEi+0ncfKBT6BKpnqOIdECgYEAiwQc0RHhHBq8Xr3xXIMK
  CEk4K/U6SsfO6gV35LV8aZVNJb00c9zw2y9Ec67kkgDIPPPpeh9VRAaRXofBKjfF
  i6pOjXunU2gjhZjhNrKihozQLn4aq81dYzPU4OfRiXuWqTMLijBM6MvxCEuVFEYr
  GCqh3CM6SQGwWyFVjAVrqkkCgYBnRZgWT7kdpEgSNThtGCUww+6fmz5Eqmu6h2s3
  d24DXU+fEbc0vesZLM4gCwWpnUJU+/TLvN942kPcsWN1wjAaZ6VADztNd9YB2WgB
  mL+u9OD8tWk7e6XmGmheiZSadVinV4JBZ0yfRjSWgHuXXXaYL0MUISIw2BmMoeka
  nodG8QKBgQCZrt4RpJLtEZ4HJemofqEoINzCCbrxPNZjjqnARbyHdbW/ApIV/8QB
  /pBQObNogsnkTg8yh+5/6Us6PqKRgZnobCGzuslW50iOFfMBPlMPObRUGTxqhYDc
  m3B3Fvtglte5kzBRzo4ebT9hGt62EE8/JfRPulsK8f8jEmyX8URWcQ==
  -----END RSA PRIVATE KEY-----
  EOF
  chown -R root:root /root/.ssh
  chmod 0600 /root/.ssh/initscript_deploy_key /root/.ssh/config
  yum install -y git &&  git clone git@github.com-repo-0:cpchainnetworkio/ec2_init.git
  bash ec2_init/init.sh
  bash ec2_init/node-exporter/install_node_exporter.sh