project: gameplus
app: com-ng-internal
owners: tianfeng.cui
load_balancer_type: "application"
internal: true
vpc_selector:
  cidr_block: 192.168.0.0/16
  moniker: main-app
subnet_selector:
  cidr_blocks:
  - 192.168.20.0/24
  - 192.168.21.0/24
  - 192.168.22.0/23
security_groups: 
  - sg-03579e416de884693
target_groups: |
  - name_prefix: nginx-
    backend_protocol: HTTP
    backend_port: 80
    target_type: instance
    deregistration_delay: 10
    stickiness: 
      enabled: true
      type: lb_cookie
    health_check:
      enabled: true
      interval: 30
      path: /
      port: 80
      protocol: HTTP
      matcher: 200
    protocol_version: HTTP1
    targets:
      snapshot0:
        target_id: i-068a9a9d1a2314f24
        port: 80
https_listeners: |
  - port: 443
    protocol: HTTPS
    certificate_arn: arn:aws:acm:ap-southeast-1:703585791570:certificate/a2d5418f-2810-4046-99cf-b16152fab329
    action_type: fixed-response
    fixed_response: 
      content_type: text/plain
      status_code: "404"
https_listener_rules: |
  - https_listener_index: 0
    conditions:
    - path_patterns:
      - /*
    actions:
    - type: forward
      target_group_index: 0
http_tcp_listeners: |
  - port: 80
    protocol: HTTP
    action_type: redirect
    redirect:
      port: 443
      protocol: HTTPS
      status_code: HTTP_301