project: automation
app: terragruntactionsrunner
owners: tevin.cui
trusted_role_arns:
- arn:aws:iam::191913451055:role/githubactions-oidc-terragrunt
trusted_role_actions:
- sts:AssumeRole
- sts:TagSession
role_requires_mfa: false
custom_role_policy_arns: 
- arn:aws:iam::aws:policy/AdministratorAccess
inline_role_policies:cd